name: sync

on:
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Git Sync Action
        uses: wei/git-sync@v3.0.0
        with:
          source_repo: "ocdtrekkie/HAController"
          source_branch: "refs/remotes/source/*"
          destination_repo: "${{ secrets.SYNC_URL }}"
          destination_branch: "refs/heads/*"
